//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int id_zakaz { get; set; }
        public Nullable<int> id_tovar { get; set; }
        public Nullable<int> colichestvo { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string punkt_vidachi { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual user user { get; set; }
    }
}
